// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1PWqU_3NSdRzHN8VXN1CfvnaKw9SITC4',
    appId: '1:326552966863:android:fae6dd2db80312012509ba',
    messagingSenderId: '326552966863',
    projectId: 'attendstore-536ec',
    databaseURL: 'https://attendstore-536ec-default-rtdb.firebaseio.com',
    storageBucket: 'attendstore-536ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzsciDPLkPem342Yxv-0Auxq_4QWRgF_k',
    appId: '1:326552966863:ios:08f18049ff2865632509ba',
    messagingSenderId: '326552966863',
    projectId: 'attendstore-536ec',
    databaseURL: 'https://attendstore-536ec-default-rtdb.firebaseio.com',
    storageBucket: 'attendstore-536ec.firebasestorage.app',
    iosBundleId: 'com.example.attendstore',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGQyEyvWbSgsNY43xJ2KaEAuubfP3_ZEw',
    appId: '1:326552966863:web:cd6f9078ccf6ddb22509ba',
    messagingSenderId: '326552966863',
    projectId: 'attendstore-536ec',
    authDomain: 'attendstore-536ec.firebaseapp.com',
    databaseURL: 'https://attendstore-536ec-default-rtdb.firebaseio.com',
    storageBucket: 'attendstore-536ec.firebasestorage.app',
  );

}